### ISSUE TITLE
BUG: Abandoned growable industry buildings get rebuild, but immediately turn abandoned again.

### ISSUE THREAD

**Issue by Sipke82** [keallu/CSL-RebuildIt#1]
BUG: Abandoned growable industry buildings get rebuild, but immediately turn abandoned again.

I plop all buildings, the growable industry buildings are marked as historical buildings.

**Comment by Sipke82** [comment]
I can confirm that it does also happen with commercial buildings.

**Comment by Sipke82** [comment]
Can no longer reproduce, i suspect incompatibility with no abandonment.

**Comment by Sipke82** [comment]
Ugh... Now its happening again in my main city... not sure what is causing this probabaly another mod conflict:
I use these mods:
https://steamcommunity.com/sharedfiles/filedetails/?id=1565457981

**Comment by keallu** [comment]
This issue have been fixed in the latest version, 1.8, which was released to the workshop today.
